Friendships v1
Henryhaulka/ror-social-scaffold pull request #2
Opened 2021-06-29 15:32 UTC by ShinobiWarior

## In this Milestone we:
-Created a model with associations and all requested features for friendships (you can find all requirements in [Social Network](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/) )
-Created  unit and integrations tests

2021-06-29 17:04 UTC, SajjadAhmad14 commented on app/views/users/show.html.erb
> +  <% end %>
Please move this logic to app/helpers. [OPTIONAL]

2021-06-29 17:05 UTC, SajjadAhmad14 commented on app/views/users/_user.html.erb
> +        <%= link_to 'Invite to friendship',  friendships_path(user_id: user.id), method: :post, action: :confirm, class: 'btn-green' %>
Please move this logic to app/helpers. [OPTIONAL]

2021-06-29 17:05 UTC, SajjadAhmad14 commented on app/views/posts/_post.html.erb
> +      <% end %>
Please move this logic to app/helpers. [OPTIONAL]

2021-06-29 17:06 UTC, SajjadAhmad14 commented on app/views/friendships/index.html.erb
> +<% end %>
Please move this logic to app/helpers. [OPTIONAL]

2021-06-29 17:06 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] You have mastered Git flow.
- [ ] PR title and summary are descriptive.
- [ ] All the specs are passing.
## To Improve 🙏
- [ ] Please add integration tests for the friendship feature.
- [ ] Please see inline comments for reference.
# Optional
- [ ] Views should be completely separate from app logic. You can move view-related logic to app/helpers.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-30 13:07 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coders, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The added tests cater to all methods. 👍🏽 

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-07-01 08:02 UTC, merged